# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rag-playground',
                'doc_host': 'https://praneethys.github.io',
                'git_url': 'https://github.com/praneethys/rag-playground',
                'lib_path': 'rag_playground'},
  'syms': {'rag_playground.core': {'rag_playground.core.foo': ('core.html#foo', 'rag_playground/core.py')}}}
